services:
  coordinator-database:
    container_name: coordinator-database
    image: redis:latest
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "${COORDINATOR_REDIS_PORT:-6379}:${COORDINATOR_REDIS_PORT:-6379}"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - coordinator-redis:/data

  coordinator-service:
    container_name: coordinator-service
    build:
      context: ../..
      dockerfile: apps/coordinator/Dockerfile
    env_file:
      - ./.env
    environment:
      # Check Dockerfile to see where bin is downloaded
      - COORDINATOR_RAPIDSNARK_EXE=/home/node/rapidsnark/build/prover
    volumes:
      - coordinator-data:/app
    ports:
      - "${COORDINATOR_PORT:-3001}:${COORDINATOR_PORT:-3001}"

volumes:
  coordinator-data:
    driver: local
  coordinator-redis:
    driver: local
