name: Checks

on:
  push:
    branches: [dev]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        command: ["prettier", "types", "lint:ts", "lint:sol"]

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Update npm to latest version
        run: npm install --global npm@latest

      - name: Build
        run: |
          npm install
          npm run build

      - name: ${{ matrix.command }}
        run: npm run ${{ matrix.command }}
