name: Circuit

on:
  push:
    branches: [ master, audit, dev ]
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Update npm to latest version
        run: npm install --global npm@latest

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            build-essential \
            libgmp-dev \
            libsodium-dev \
            nasm \
            nlohmann-json3-dev

      - name: Build maci-circuits package
        run: |
          npm install
          npm run bootstrap
          npm run build

      - name: Download circom Binary v2.1.5
        run: |
          mkdir -p /home/runner/work/maci/.local/bin
          wget -qO /home/runner/work/maci/.local/bin/circom https://github.com/iden3/circom/releases/download/v2.1.5/circom-linux-amd64
          chmod +x /home/runner/work/maci/.local/bin/circom

      - name: Build circuits
        run: npm run build-test-circuits
        working-directory: circuits
      
      - name: Launch circom-helper
        run: |
          # circom-helper exposes a JSON-RPC API which allows developers to generate witnesses and access signal values
          nohup npm run circom-helper &

          # Wait until circom-helper listen to port 9001
          while [[ "$(lsof -i :9001)" -eq '0' ]]; do sleep 1; done
        working-directory: circuits
      
      - name: Test circuits
        run: npm run test
        working-directory: circuits
