name: Release

on:
  push:
    tags: ["*"]

jobs:
  draft-release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Draft Release
        run: |
          gh release create ${GITHUB_REF##*/} --title "${GITHUB_REF##*/}" --draft --generate-notes --prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Initialize Project
        run: |
          git config --global url."https://github.com/".insteadOf git://github.com/
          npm install
          npx lerna bootstrap
          npm run build

      - name: Compile Contracts
        run: |
          cd contracts
          npm run compileSol

      - name: Publish NPM
        run: |
          npx lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
