name: E2E

on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Check for changes in the 'circuit' folder
      - name: Get changed files
        id: get-changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "csv"

      - name: Check for changes in 'circuit' folder 
        id: check_changes
        run: |
          CHANGED_FILES=${{ steps.get-changed-files.outputs.all }}
          if echo "$CHANGED_FILES" | grep -q "\.circom"; then
            echo "CHANGED=true" >> $GITHUB_ENV
            echo "Circuits have changes."
          else
            echo "CHANGED=false" >> $GITHUB_ENV
            echo "No changes on circuits."
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            build-essential \
            libgmp-dev \
            libsodium-dev \
            nasm \
            nlohmann-json3-dev

      - name: Initialize Project
        run: |
          npm install
          npm run bootstrap
          npm run build

      - name: Download rapidsnark (1c137)
        run: |
          mkdir -p ~/rapidsnark/build
          wget -qO ~/rapidsnark/build/prover https://maci-devops-zkeys.s3.ap-northeast-2.amazonaws.com/rapidsnark-linux-amd64-1c137
          chmod +x ~/rapidsnark/build/prover

      - name: Download circom Binary v2.1.6
        run: |
          mkdir -p /home/runner/work/maci/.local/bin
          wget -qO /home/runner/work/maci/.local/bin/circom https://github.com/iden3/circom/releases/download/v2.1.6/circom-linux-amd64
          chmod +x /home/runner/work/maci/.local/bin/circom

      - name: Generate zkeys
        if: ${{ env.CHANGED == 'true' }}
        run: |
          cd cli
          mkdir -p zkeys
          wget -qO zkeys/powersOfTau28_hez_final_20.ptau https://maci-devops-zkeys.s3.ap-northeast-2.amazonaws.com/powersOfTau28_hez_final_20.ptau
          npx zkey-manager compile -c ./zkeys.config.yml
          npx zkey-manager genZkeys -c ./zkeys.config.yml

      - name: Download zkeys
        if: ${{ env.CHANGED == 'false' }}
        run: |
          cd integrationTests
          npm run download-zkeys

      - name: Bespoke Test
        run: |
          cd cli
          npm run test

      - name: Integration Test
        run: |
          cd integrationTests
          npm run test
